[package]

authors = ["Christian Sdunek <me@systemcluster.me>"]
categories = ["compression", "filesystem", "command-line-utilities"]
keywords = ["witcher-3", "modding", "games"]
description = "Utility for packing, unpacking and analyzing The Witcher 3 bundle files"
edition = "2021"
include = [
  "Cargo.toml",
  "src/**/*",
  "LICENSE",
]
license = "BSD-2-Clause"
name = "w3edit"
readme = "README.md"
repository = "https://github.com/Systemcluster/w3edit"
version = "0.0.1"
rust-version = "1.92.0"

[lib]

name = "w3edit"
path = "src/lib.rs"

[[bin]]

name = "w3edit"
path = "src/main.rs"
required-features = ["cli"]

[profile.dev]

debug = 1
debug-assertions = true
incremental = true
lto = "off"
opt-level = 0
panic = "unwind"

[profile.dev.package."*"]

inherits = "dev"
opt-level = 2

[profile.release]

codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 's'
panic = "abort"
strip = "none"

[dependencies]

log = { version = "0.4" }
thiserror = { version = "2.0" }
flate2 = { version = "1.1" }
lz4 = { version = "1.28" }
snap = { version = "1.1" }
zerocopy = { version = "0.8", features = ["derive"] }

clap = { version = "4.6", features = ["std", "color", "suggestions", "derive", "unicode", "wrap_help"], optional = true }
console = { version = "0.16", optional = true }
env_logger = { version = "0.11", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

[features]

default = ["cli"]
cli = ["dep:clap", "dep:console", "dep:env_logger", "dep:serde", "dep:serde_json"]

[dev-dependencies]

memmap2 = "0.9"

[package.metadata.docs.rs]

rustdoc-args = ["--cfg", "docsrs"]
all-features = true
